### ISSUE TITLE
Bug with jquery.js sourcecode.

### ISSUE THREAD

**Issue by telegraphinho** [6to5/6to5-sublime#11]
jQuery version: 1.11.2(didn't check other versions)
Line #: 2356
Screenshot of the problem: http://i.imgur.com/H5eQJ70.png
It stumbles on this whole line(doesn't highlight any syntax for some reason) AND it doesn't highlight syntax in the subsequent lines unless you remove the ternary operator in the end(question mark and further till the closing curly bracket).

If you remove this whole line it also fixes the problem.

It works fine with regular Javascript Syntax. Any ideas as to what causes it?

**Comment by telegraphinho** [comment]
I guess it's Javascript Next's fault. It's broken there too.

**Comment by Dashed** [comment]
@telegraphinho would you be able to find a minimal example?

**Comment by telegraphinho** [comment]
@Dashed Unfortunately it's not possible. It seems, that also has something to do with the size of the file. If i extract the function or expression in question into it's own file - syntax highlighting works fine. If i remove all preceding lines in jquery.js it also works fine.

Also found the same thing in angular.js source code. This time on line #6882. And the same thing happens. Syntax highlighting works fine if you remove all preceding lines or extract the function in question into it's own file. Is there anything else i can do?

**Comment by zertosh** [comment]
I noticed a problem with ternaries yesterday. I was looking at prettified version of a minified file - my guess is that the minification does really weird things with ternaries. These changes might have something to do with  it https://github.com/Benvie/JavaScriptNext.tmLanguage/commit/da5a5529deeb72eefc98d2d48183bc8bc54e6173 and https://github.com/Benvie/JavaScriptNext.tmLanguage/commit/732f5a3db13b7008382e594519f816064692802f. Sadly, I couldn't stop what I was doing to debug it. But from your screenshot it seems that you don't have a ternary that could be causing the same problem. @telegraphinho Can you make a gist with the file you're looking at from the screenshot?

**Comment by telegraphinho** [comment]
@zertosh https://gist.github.com/telegraphinho/f6c6677821cead79f604 . It's an original(not unminified) jquery@1.11.2

**Comment by Dashed** [comment]
Oh haha. I didn't realize it's the actual jQuery source code.

**Comment by zertosh** [comment]
@telegraphinho fixed in https://github.com/6to5/6to5-sublime/pull/15. I should get picked up by Package Control in an hour or so.
