### ISSUE TITLE
Ternaries with spaces before colon breaks highlighting.

### ISSUE THREAD

**Issue by STRML** [6to5/6to5-sublime#13]
For example:

![Imgur](http://i.imgur.com/LCaV8gx.jpg)

This appears to be caused by the space in the ternary.

Copy-paste this snippet to your editor:

```javascript
'use strict';
var React = require('react');
function test() {
  var a = "bar";
  return (
    <div foo="bar" className={"foo" + (a ? 'foo' :'bar')} herp="derp">
      <div foo="bar" className={"foo" + (a ? 'foo':'bar')} herp="derp" />
    </div>
  );
}
```

Play with spaces before/after the `:`.

**Comment by STRML** [comment]
As a more minimal test, simply try 

`(true ? 'bar' : 'bar');`

Note that the red highlighting on the colon disappears and reappears if the space before it is removed.

**Comment by STRML** [comment]
I am not familiar with the `tmLanguage` spec, but this appears to fix it:

Change [L1516](https://github.com/6to5/6to5-sublime/blob/956c85261e55f2b914eab90e2bb447344cfaa6bf/JavaScript%206to5.tmLanguage#L1516), which reads:

```
<string>:</string>
```

to:

```
<string>\ *:</string>
```

**Comment by zertosh** [comment]
@STRML I have to look into this. A change was recently introduced into JavaScriptNext and I think it's causing other issues too (See https://github.com/6to5/6to5-sublime/issues/11#issuecomment-70836428)

**Comment by zertosh** [comment]
@STRML fixed in https://github.com/6to5/6to5-sublime/pull/15
