### ISSUE TITLE
regex char escaping throws off syntax highlighter

### ISSUE THREAD

**Issue by mshick** [6to5/6to5-sublime#17]
See screenshots -- top is with the built-in JS syntax, and it looks fine

![screen shot 2015-01-27 at 11 20 53 pm](https://cloud.githubusercontent.com/assets/277401/5932403/395f5302-a67b-11e4-85c9-91b2b5378997.png)

bottom here is with 6to5, and you see it thinks something is unclosed... Scripts eval fine, no hidden chars, etc.

![screen shot 2015-01-27 at 11 21 07 pm](https://cloud.githubusercontent.com/assets/277401/5932407/51f1d282-a67b-11e4-8b28-867d40b1a312.png)

**Comment by hawkrives** [comment]
I can second this report; the attached code block highlights everything after the start of the regex as a regex.

```js
let spacedOutDays = daystring.replace(/([A-Z][a-z]?)\/?/g, '$1 ')
// The regex sticks an extra space at the end. Remove it.
```

![screen shot 2015-01-28 at 12 08 45 am](https://cloud.githubusercontent.com/assets/464441/5933172/dbc4a11e-a681-11e4-99ef-9b7d458ded86.png)

**Comment by zertosh** [comment]
I can't seem to reproduce this. Can I get more details? Like a gist of the surrounding context?
![wjxzf](https://cloud.githubusercontent.com/assets/830952/5943442/05802292-a6ed-11e4-9a2f-014c42438864.png)

**Comment by mshick** [comment]
Sure, this trips it:

https://gist.github.com/mshick/bb42f2165efdc3c573e9

![screen shot 2015-01-28 at 1 05 34 pm](https://cloud.githubusercontent.com/assets/277401/5943605/5f454838-a6ee-11e4-9372-e67c65543e18.png)

**Comment by mshick** [comment]
I'm using v1.0.3 according to package manager.

**Comment by zertosh** [comment]
@mshick... still can't reproduce it
![dajlb](https://cloud.githubusercontent.com/assets/830952/5944198/041791dc-a6da-11e4-9666-455cc106a89e.png)
![pmcuo](https://cloud.githubusercontent.com/assets/830952/5944199/0418ac66-a6da-11e4-896d-8a333765af86.png)
![yinbi](https://cloud.githubusercontent.com/assets/830952/5944200/041a436e-a6da-11e4-8c32-ea138082fcc6.png)

**Comment by zertosh** [comment]
@mshick why is the open parens on `replace` outlined?

**Comment by hawkrives** [comment]
@zertosh if I stick my example into a blank file and set the syntax to Javascript 6to5, it triggers the bug, with package v.1.0.3.

```js
let spacedOutDays = daystring.replace(/([A-Z][a-z]?)\/?/g, '$1 ')
// The regex sticks an extra space at the end. Remove it.
```

**Comment by mshick** [comment]
@zertosh I’m not sure why it’s outlined, but I assume that’s the heart of the issue. If I remove the escaped / things go back to normal. If I disable BracketHighlighter (which does the outlining)  the outline and question mark go away, but the syntax coloring remains messed up.

**Comment by zertosh** [comment]
@mshick I quickly looked at `BracketHighlighter` and it seems like it messes with the syntax scopes. Before I go down that rabbit hole, can you share with me a quick list of what other plugins you have installed? Thanks!

**Comment by mshick** [comment]
Sure, give me a sec and I’ll work my way through them and see if I can find an offender.

**Comment by mshick** [comment]
@zertosh I’ve disabled every package aside from Package Manager and 6to5 and I still have the problem.

I’ll try a fresh install and see what happens…

**Comment by mshick** [comment]
Here is the list of disabled packages, FYI:

		"SidebarEnhancements",
		"BracketHighlighter",
		"Stylus",
		"EditorConfig",
		"SublimeLinter",
		"Vintage",
		"GitGutter",
		"SublimeGit",
		"Handlebars",
		"SublimeLinter-jshint",
		"SublimeLinter-jsxhint",
		"Alignment",
		"WhoCalled Function Finder",
		"Predawn",
		"LESS",
		"JavaScript Completions",
		"JavaScript & NodeJS Snippets"

**Comment by mshick** [comment]
Also, I’m on ST3, build 3065. I’ll try the latest dev build, 3066.

**Comment by mshick** [comment]
3066 had the same issue.

3066 installed completely fresh, with only package control and 6to5 installed has the same problem.

Forgive the question, but are you sure you have the 6to5 syntax mode selected? When I brought up the fresh install things looked good for a sec, until I changed the syntax to use 6to5.

**Comment by zertosh** [comment]
@mshick Thanks for the details. I tried the version that's distributed via Package Control and local non-packaged one. I'll dig into this more tonight.

@Dashed have you had these issues?

**Comment by Dashed** [comment]
@zertosh Can't replicate. I'm using Monokai Extended color scheme.  Using Sublime Text 3 for OSX (build 3065):

![screen shot 2015-01-28 at 7 05 22 pm](https://cloud.githubusercontent.com/assets/139499/5949877/ab0795f0-a720-11e4-8b3d-c26e52c4570d.png)

I updated all installed packages. I restarted Sublime Text as well with no regression.

My `Package Control.sublime-settings`:
```
{
	"in_process_packages":
	[
	],
	"installed_dependencies":
	[
		"0_package_control_loader",
		"bz2"
	],
	"installed_packages":
	[
		"6to5",
		"AAAPackageDev",
		"Better CoffeeScript",
		"Better TypeScript",
		"BracketHighlighter",
		"DocBlockr",
		"FileDiffs",
		"GitGutter-Edge",
		"HTML-CSS-JS Prettify",
		"Jade",
		"JavaScript & NodeJS Snippets",
		"JavaScriptNext - ES6 Syntax",
		"Markdown Extended",
		"MarkdownEditing",
		"Monokai Extended",
		"Package Control",
		"Pretty JSON",
		"ReactJS",
		"SideBarEnhancements",
		"Stylus"
	]
}
```

**Comment by Dashed** [comment]
Wondering if this is a color scheme issue...

**Comment by hawkrives** [comment]
I can replicate it with both my current color scheme and the default Monokai. I'll try it on a default install later tonight.

**Comment by mshick** [comment]
I get the same results regardless of color scheme, and since BracketHighlighter is tripped as well, it has to be the syntax.

I believe I just found the reason for the different results we're seeing. If I have "JavaScriptNext - ES6 Syntax" installed then everything looks right / works properly, regardless of whether my doc is using 6to5 or JSNext as the syntax setting.

@Dashed can you try uninstalling that syntax and seeing if you can replicate?

**Comment by mshick** [comment]
(it makes no sense that one syntax would affect another, but that's definitely what I'm seeing)

**Comment by zertosh** [comment]
@mshick ok i'm seeing it now. if I remove jsnext, i see your breakable. i'll investigate why

**Comment by zertosh** [comment]
derp. i think i found it. i think it's a UUID conflict.

**Comment by Dashed** [comment]
@zertosh Haha! If I uninstall jsnext, all my js code is white! :laughing:

**Comment by zertosh** [comment]
Thanks @mshick and @hawkrives for helping out with this. I just published a fix. You've got to give Package Control like an hour to update

**Comment by hawkrives** [comment]
@zertosh Thank you! Keep up the good work.

**Comment by mshick** [comment]
Thanks so much!

**Comment by Dashed** [comment]
Updated, works fine now :)
