### ISSUE TITLE
ES6/JSX Class methods

### ISSUE THREAD

**Issue by qmmr** [6to5/6to5-sublime#19]
Do you plan to add snippets that would use ES6 concise class methods? I've added them to my [ES6/JSX branch](https://github.com/qmmr/sublime-react/tree/ES6/JSX/snippets/js) in sublime-react fork.

**Comment by Dashed** [comment]
I might +1 on this since it's something 6to5 supports.

I still haven't gotten used to typing out ES6 concise methods in objects yet :stuck_out_tongue:.

**Comment by zertosh** [comment]
@qmmr and @Dashed all of our snippets already use concise method definition syntax, and even the "component skeleton" uses `import`

**Comment by qmmr** [comment]
Oh, sorry my bad, I had installed react-snippets which was shadowing 6to5. I've removed the old package and everything works :+1:

**Comment by Dashed** [comment]
Hah. Apparently I had a similar issue :smile:
