### ISSUE TITLE
Sublime functions list

### ISSUE THREAD

**Issue by max-mykhailenko** [6to5/6to5-sublime#22]
How I can add es6 method to function list?

![screen shot 2015-02-02 at 11 04 58 am](https://cloud.githubusercontent.com/assets/1213198/5998044/945a6626-aacb-11e4-9f27-8ba82cad1872.png)
![screen shot 2015-02-02 at 11 05 14 am](https://cloud.githubusercontent.com/assets/1213198/5998045/945abbb2-aacb-11e4-9a49-9410b4b9785f.png)

**Comment by zertosh** [comment]
Hey @max-mykhailenko, this is a known issue. The thing is that short method definitions are not scoped as methods so sublime doesn't show them in the symbols list. I haven't figured out a good way to match them yet, but I welcome PRs :)

**Comment by zertosh** [comment]
@max-mykhailenko, this is fixed in https://github.com/6to5/6to5-sublime/pull/25. Package Control should pick up the update in like an hour.
