### ISSUE TITLE
Use of a < with no whitespace near it results in weird colors

### ISSUE THREAD

**Issue by hawkrives** [6to5/6to5-sublime#29]
![screen shot 2015-02-12 at 10 44 32 pm](https://cloud.githubusercontent.com/assets/464441/6182405/bbec08bc-b308-11e4-942a-8c39cf185238.png)
```js
function tableToJson(table) {
	// from http://johndyer.name/html-table-to-json/
	var data = []; // first row needs to be headers
	var headers = [];
	for (var i=0; i < table.rows[0].cells.length; i++) {
		headers[i] = table.rows[0].cells[i].innerHTML.toLowerCase().replace(/ /gi,'')
	}
	// go through cells
	for (var i=1; i<table.rows.length; i++) {
		var tableRow = table.rows[i]
		var rowData = {}
		for (var j=0; j < tableRow.cells.length; j++) {
			rowData[ headers[j] ] = tableRow.cells[j].innerHTML;
		}
		data.push(rowData)
	}
	return data
}
```

or even as little code as

![screen shot 2015-02-12 at 10 45 50 pm](https://cloud.githubusercontent.com/assets/464441/6182418/e8cafe92-b308-11e4-8b77-ce14f417c798.png)
```js
i<table
return data
```

If I add a space to the right side of the `<`, all is well.

Because it's a `<`, I'm thinking it has something to do with the JSX highlighting, maybe?

Let me know if you need any more information.

**Comment by zertosh** [comment]
Yeah, I've known about this but I don't think there's a solution. Sublime can't match across new lines, but a single JSX tag can run multiple lines - in fact, it's a very common pattern:

```js
<div className='PanelSearch'>
  Search<input
    className='PanelSearch-field'
   /* comments */
    onChange={this.onInputChangeHandler}
    onKeyDown={this.onInputKeyDownHandler}
    value={props.query}
  />
</div>
```

So we only match the opening part of the tag (e.g.: `<Tag`) then try to match attributes and comments, since those can be on another line.

**Comment by Dashed** [comment]
Are semicolons allowed inside JSX tags? If not, maybe that can be a heuristic to differentiate JSX tags from comparison operator.

**Comment by zertosh** [comment]
@Dashed good call! Can you and @hawkrives give https://github.com/6to5/6to5-sublime/pull/33 a test drive before I merge it?

**Comment by zertosh** [comment]
@hawkrives I just pushed the fix for this issue in [v2.0.0](https://github.com/6to5/6to5-sublime/releases/tag/v2.0.0) - should be picked up by Package Control within the hour.

**Comment by hawkrives** [comment]
Excellent. Sorry I didn't get around to testing this— today was a bit hectic. 




I'll see if I spot anything!

**Comment by zertosh** [comment]
no worries!
