### ISSUE TITLE
Label comparison screenshot

### ISSUE THREAD

**Issue by Dashed** [6to5/6to5-sublime#3]
I think it's useful to label which frame of the comparison gif uses which syntax theme:
![screen2](https://cloud.githubusercontent.com/assets/139499/5786680/4b82e9da-9db7-11e4-83d0-9d65674f3921.gif)

**Comment by Dashed** [comment]
GitHub css resizes the gif width-wise; looks nice if you open the gif in a separate tab.

**Comment by zertosh** [comment]
Derp. I didn't even label it in the README.

**Comment by Dashed** [comment]
@zertosh You can take the gif if you want. Or do your own preferred labelling.

**Comment by zertosh** [comment]
@Dashed ugh. now it decides to autocomplete. first time ever. weird.
