### ISSUE TITLE
`async` and `await` keywords aren't highlighted

### ISSUE THREAD

**Issue by sebmck** [6to5/6to5-sublime#30]
![screen shot 2015-02-13 at 4 27 47 pm](https://cloud.githubusercontent.com/assets/853712/6182690/44436c52-b39d-11e4-999a-af64b14a3f1d.png)

**Comment by zertosh** [comment]
Might be a color scheme issue. `async` is matching as `storage.type.js` - so the same as `const`, `let`, and `var`. And, `await` is matching as `keyword.operator.js` - same as `delete`, `in`, `instanceof`, `new`, `of`, `typeof`, `void`, `with`. BUT, i'm seeing that `var` and `of` in the `for` are colored. Can you gist me a a full file?

PS: If you press `shift+ctrl+p`, Sublime will show you the matching scope in the status bar for wherever the cursor is.

![lzkyh](https://cloud.githubusercontent.com/assets/830952/6190152/f0ca589e-b36d-11e4-83fc-282f64446bce.png)

**Comment by sebmck** [comment]
Ah, duh. Looks like that'll have to be added to Oceanic Next then. Thanks! /cc @voronianski

**Comment by zertosh** [comment]
@sebmck If you missed it, I added more `async` and generator function goodness in https://github.com/babel/babel-sublime/issues/52 a few days ago

**Comment by sebmck** [comment]
@zertosh Woo, awesome!
