### ISSUE TITLE
Does not highlight functions in class

### ISSUE THREAD

**Issue by SomeKittens** [6to5/6to5-sublime#34]
![screen shot 2015-02-13 at 2 26 44 pm](https://cloud.githubusercontent.com/assets/1616464/6196332/5d550d06-b38c-11e4-8ac6-0cb9c8065a96.png)

I'd expect `constructor` (as well as other class functions) to be in green, with `this` in blue.

**Comment by zertosh** [comment]
You're probably using the default Monokai scheme, try `Sublime Text -> Preferences -> Color Scheme -> 6to5 -> Monokai Phoenix`

![mlkev](https://cloud.githubusercontent.com/assets/830952/6196754/d3d8aa1a-b3a9-11e4-8fda-f1dc22debf3e.png)

**Comment by SomeKittens** [comment]
Yep, that was it.  Not quite sure how I feel about switching color schemes for a syntax highlighter, but it works!

The docs weren't quite clear that this change needed to be made - could that be updated?

**Comment by zertosh** [comment]
We have the [Setting a Color Scheme](https://github.com/6to5/6to5-sublime#setting-a-color-scheme) section. What else do you think it should say?

For context: The syntax definition works regardless of color scheme. It just so happens that the stock "Monokai" chooses not to color certain constructs. You don't have to use the Monokai we provide. For example, I use https://github.com/zenorocha/dracula-theme - there is nothing ES6/JSX specific about it. You can use tons of other color schemes that provide more coverage than the stock Monokai.

**Comment by SomeKittens** [comment]
Ah, that makes a lot of sense - thanks!

**Comment by hiscodeness** [comment]
I noticed that syntax highlighting of class functions breaks with Allman style (brace on new line).

![image](https://cloud.githubusercontent.com/assets/8625258/6959433/804b4284-d921-11e4-8a62-0bfc8d93fa66.png)

Is there a workaround for this?

**Comment by zertosh** [comment]
@hiscodeness I'm afraid not. https://github.com/babel/babel-sublime/issues/50 goes into a bit more detail. In this case, there is no way to tell apart between `constructor(imageDefinition)` being a function call or method definition when the `{` is on another line.

**Comment by hiscodeness** [comment]
That's unfortunate, but totally understandable. Thanks for the response!
